#!/bin/bash
#
#PBS -N 4p4p1000pp08a
#PBS -M iahanor@vols.utk.edu
#PBS -m abe
#PBS -A ACF-UTK0011
#PBS -o /lustre/haven/user/iahanor/branchandbound/Train/4p/4p1000pp08aO.txt
#PBS -e /lustre/haven/user/iahanor/branchandbound/Train/4p/4p1000pp08aE.txt
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=4
#PBS -l partition=gpu
#PBS -l feature=cascadelake_gpu

cd /lustre/haven/user/iahanor/branchandbound/Train/4p
mkdir 4p1000pp08aF
cd 4p1000pp08aF

git clone https://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@github.com/izuwaa/Diversitree.git
cd Diversitree
module load gcc/6.3.0
module load cmake

cmake -Bbuild -H. -DSCIP_DIR=/lustre/haven/user/iahanor/branchandbound/scipoptsuite-7.0.3/installDir/lib/cmake/scip -DGMP_INCLUDE_DIR=/sw/cs400_centos7.3_acfsoftware/gmp/5.1.1/centos7.3_intel17.2.174/include
cmake --build build
echo "module loaded"

cd /lustre/haven/user/iahanor/branchandbound/Train/4p/4p1000pp08aF/Diversitree
/lustre/haven/user/iahanor/branchandbound/Train/4p/4p1000pp08aF/Diversitree/build/diversitree 4p1000pp08a.txt problemOptions , solverParams.txt solverOptions :
echo "module I am done"