#!/bin/bash
#
#PBS -N 6p6p50set1ch
#PBS -M iahanor@vols.utk.edu
#PBS -m abe
#PBS -A ACF-UTK0011
#PBS -o /lustre/haven/user/iahanor/branchandbound/Train/6p/6p50set1chO.txt
#PBS -e /lustre/haven/user/iahanor/branchandbound/Train/6p/6p50set1chE.txt
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=4
#PBS -l partition=gpu
#PBS -l feature=cascadelake_gpu

cd /lustre/haven/user/iahanor/branchandbound/Train/6p
mkdir 6p50set1chF
cd 6p50set1chF

git clone https://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@github.com/izuwaa/Diversitree.git
cd Diversitree
module load gcc/6.3.0
module load cmake

cmake -Bbuild -H. -DSCIP_DIR=/lustre/haven/user/iahanor/branchandbound/scipoptsuite-7.0.3/installDir/lib/cmake/scip -DGMP_INCLUDE_DIR=/sw/cs400_centos7.3_acfsoftware/gmp/5.1.1/centos7.3_intel17.2.174/include
cmake --build build
echo "module loaded"

cd /lustre/haven/user/iahanor/branchandbound/Train/6p/6p50set1chF/Diversitree
/lustre/haven/user/iahanor/branchandbound/Train/6p/6p50set1chF/Diversitree/build/diversitree 6p50set1ch.txt problemOptions , solverParams.txt solverOptions :
echo "module I am done"